# Generated by Django 3.1.4 on 2020-12-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('a_id', models.AutoField(primary_key=True)),
                ('a_text', models.TextField()),
                ('a_author', models.CharField(max_length=50)),
                ('a_creation_time', models.DateTimeField(auto_now_add=True)),
                ('a_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_id', models.AutoField(primary_key=True)),
                ('q_text', models.TextField()),
                ('q_author', models.CharField(max_length=50)),
                ('q_creation_time', models.DateTimeField(auto_now_add=True)),
                ('q_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('c_id', models.AutoField(primary_key=True)),
                ('c_text', models.TextField()),
                ('c_author', models.CharField(max_length=50)),
                ('c_creation_time', models.DateTimeField(auto_now_add=True)),
                ('c_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoraBase.answers')),
                ('c_replyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoraBase.comments')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='a_ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoraBase.questions'),
        ),
    ]
