# Generated by Django 3.1.4 on 2020-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoraBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='a_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='a_creation_time',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='a_ques',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='a_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='a_votes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_ans',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_creation_time',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_replyto',
            new_name='replyto',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_creation_time',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_votes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='q_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
