# Generated by Django 3.1.4 on 2020-12-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoraBase', '0002_auto_20201219_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='ans',
            new_name='answer',
        ),
    ]
