# Generated by Django 3.1.4 on 2020-12-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoraBase', '0003_auto_20201219_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='replyto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quoraBase.comments'),
        ),
    ]
