# Generated by Django 3.1.4 on 2020-12-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoraBase', '0004_auto_20201219_2224'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
