# Generated by Django 3.1.4 on 2020-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoraBase', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
